
//input ports
add mapped point i_clk i_clk -type PI PI
add mapped point i_rst_n i_rst_n -type PI PI
add mapped point i_wr_en i_wr_en -type PI PI
add mapped point i_rd_en i_rd_en -type PI PI
add mapped point i_din[31] i_din[31] -type PI PI
add mapped point i_din[30] i_din[30] -type PI PI
add mapped point i_din[29] i_din[29] -type PI PI
add mapped point i_din[28] i_din[28] -type PI PI
add mapped point i_din[27] i_din[27] -type PI PI
add mapped point i_din[26] i_din[26] -type PI PI
add mapped point i_din[25] i_din[25] -type PI PI
add mapped point i_din[24] i_din[24] -type PI PI
add mapped point i_din[23] i_din[23] -type PI PI
add mapped point i_din[22] i_din[22] -type PI PI
add mapped point i_din[21] i_din[21] -type PI PI
add mapped point i_din[20] i_din[20] -type PI PI
add mapped point i_din[19] i_din[19] -type PI PI
add mapped point i_din[18] i_din[18] -type PI PI
add mapped point i_din[17] i_din[17] -type PI PI
add mapped point i_din[16] i_din[16] -type PI PI
add mapped point i_din[15] i_din[15] -type PI PI
add mapped point i_din[14] i_din[14] -type PI PI
add mapped point i_din[13] i_din[13] -type PI PI
add mapped point i_din[12] i_din[12] -type PI PI
add mapped point i_din[11] i_din[11] -type PI PI
add mapped point i_din[10] i_din[10] -type PI PI
add mapped point i_din[9] i_din[9] -type PI PI
add mapped point i_din[8] i_din[8] -type PI PI
add mapped point i_din[7] i_din[7] -type PI PI
add mapped point i_din[6] i_din[6] -type PI PI
add mapped point i_din[5] i_din[5] -type PI PI
add mapped point i_din[4] i_din[4] -type PI PI
add mapped point i_din[3] i_din[3] -type PI PI
add mapped point i_din[2] i_din[2] -type PI PI
add mapped point i_din[1] i_din[1] -type PI PI
add mapped point i_din[0] i_din[0] -type PI PI

//output ports
add mapped point o_dout[31] o_dout[31] -type PO PO
add mapped point o_dout[30] o_dout[30] -type PO PO
add mapped point o_dout[29] o_dout[29] -type PO PO
add mapped point o_dout[28] o_dout[28] -type PO PO
add mapped point o_dout[27] o_dout[27] -type PO PO
add mapped point o_dout[26] o_dout[26] -type PO PO
add mapped point o_dout[25] o_dout[25] -type PO PO
add mapped point o_dout[24] o_dout[24] -type PO PO
add mapped point o_dout[23] o_dout[23] -type PO PO
add mapped point o_dout[22] o_dout[22] -type PO PO
add mapped point o_dout[21] o_dout[21] -type PO PO
add mapped point o_dout[20] o_dout[20] -type PO PO
add mapped point o_dout[19] o_dout[19] -type PO PO
add mapped point o_dout[18] o_dout[18] -type PO PO
add mapped point o_dout[17] o_dout[17] -type PO PO
add mapped point o_dout[16] o_dout[16] -type PO PO
add mapped point o_dout[15] o_dout[15] -type PO PO
add mapped point o_dout[14] o_dout[14] -type PO PO
add mapped point o_dout[13] o_dout[13] -type PO PO
add mapped point o_dout[12] o_dout[12] -type PO PO
add mapped point o_dout[11] o_dout[11] -type PO PO
add mapped point o_dout[10] o_dout[10] -type PO PO
add mapped point o_dout[9] o_dout[9] -type PO PO
add mapped point o_dout[8] o_dout[8] -type PO PO
add mapped point o_dout[7] o_dout[7] -type PO PO
add mapped point o_dout[6] o_dout[6] -type PO PO
add mapped point o_dout[5] o_dout[5] -type PO PO
add mapped point o_dout[4] o_dout[4] -type PO PO
add mapped point o_dout[3] o_dout[3] -type PO PO
add mapped point o_dout[2] o_dout[2] -type PO PO
add mapped point o_dout[1] o_dout[1] -type PO PO
add mapped point o_dout[0] o_dout[0] -type PO PO
add mapped point o_full o_full -type PO PO
add mapped point o_empty o_empty -type PO PO

//inout ports




//Sequential Pins
add mapped point o_dout[7]/q o_dout_reg[7]/Q -type DFF DFF
add mapped point o_dout[1]/q o_dout_reg[1]/Q -type DFF DFF
add mapped point o_dout[0]/q o_dout_reg[0]/Q -type DFF DFF
add mapped point o_dout[8]/q o_dout_reg[8]/Q -type DFF DFF
add mapped point o_dout[10]/q o_dout_reg[10]/Q -type DFF DFF
add mapped point o_dout[13]/q o_dout_reg[13]/Q -type DFF DFF
add mapped point o_dout[19]/q o_dout_reg[19]/Q -type DFF DFF
add mapped point o_dout[20]/q o_dout_reg[20]/Q -type DFF DFF
add mapped point o_dout[15]/q o_dout_reg[15]/Q -type DFF DFF
add mapped point o_dout[22]/q o_dout_reg[22]/Q -type DFF DFF
add mapped point o_dout[26]/q o_dout_reg[26]/Q -type DFF DFF
add mapped point o_dout[30]/q o_dout_reg[30]/Q -type DFF DFF
add mapped point o_dout[14]/q o_dout_reg[14]/Q -type DFF DFF
add mapped point o_dout[3]/q o_dout_reg[3]/Q -type DFF DFF
add mapped point o_dout[9]/q o_dout_reg[9]/Q -type DFF DFF
add mapped point o_dout[4]/q o_dout_reg[4]/Q -type DFF DFF
add mapped point o_dout[5]/q o_dout_reg[5]/Q -type DFF DFF
add mapped point o_dout[16]/q o_dout_reg[16]/Q -type DFF DFF
add mapped point o_dout[17]/q o_dout_reg[17]/Q -type DFF DFF
add mapped point o_dout[18]/q o_dout_reg[18]/Q -type DFF DFF
add mapped point o_dout[6]/q o_dout_reg[6]/Q -type DFF DFF
add mapped point o_dout[21]/q o_dout_reg[21]/Q -type DFF DFF
add mapped point o_dout[28]/q o_dout_reg[28]/Q -type DFF DFF
add mapped point o_dout[23]/q o_dout_reg[23]/Q -type DFF DFF
add mapped point o_dout[29]/q o_dout_reg[29]/Q -type DFF DFF
add mapped point o_dout[25]/q o_dout_reg[25]/Q -type DFF DFF
add mapped point o_dout[24]/q o_dout_reg[24]/Q -type DFF DFF
add mapped point o_dout[31]/q o_dout_reg[31]/Q -type DFF DFF
add mapped point o_dout[12]/q o_dout_reg[12]/Q -type DFF DFF
add mapped point o_dout[2]/q o_dout_reg[2]/Q -type DFF DFF
add mapped point o_dout[11]/q o_dout_reg[11]/Q -type DFF DFF
add mapped point o_dout[27]/q o_dout_reg[27]/Q -type DFF DFF
add mapped point mem[0][8]/q mem_reg[0][8]/Q -type DFF DFF
add mapped point mem[4][27]/q mem_reg[4][27]/Q -type DFF DFF
add mapped point mem[4][4]/q mem_reg[4][4]/Q -type DFF DFF
add mapped point mem[0][9]/q mem_reg[0][9]/Q -type DFF DFF
add mapped point mem[0][18]/q mem_reg[0][18]/Q -type DFF DFF
add mapped point mem[0][2]/q mem_reg[0][2]/Q -type DFF DFF
add mapped point mem[0][22]/q mem_reg[0][22]/Q -type DFF DFF
add mapped point mem[0][23]/q mem_reg[0][23]/Q -type DFF DFF
add mapped point mem[0][24]/q mem_reg[0][24]/Q -type DFF DFF
add mapped point mem[0][25]/q mem_reg[0][25]/Q -type DFF DFF
add mapped point mem[0][26]/q mem_reg[0][26]/Q -type DFF DFF
add mapped point mem[0][27]/q mem_reg[0][27]/Q -type DFF DFF
add mapped point mem[0][28]/q mem_reg[0][28]/Q -type DFF DFF
add mapped point mem[0][29]/q mem_reg[0][29]/Q -type DFF DFF
add mapped point mem[0][30]/q mem_reg[0][30]/Q -type DFF DFF
add mapped point mem[0][1]/q mem_reg[0][1]/Q -type DFF DFF
add mapped point mem[0][4]/q mem_reg[0][4]/Q -type DFF DFF
add mapped point mem[0][5]/q mem_reg[0][5]/Q -type DFF DFF
add mapped point mem[0][0]/q mem_reg[0][0]/Q -type DFF DFF
add mapped point mem[0][3]/q mem_reg[0][3]/Q -type DFF DFF
add mapped point mem[0][6]/q mem_reg[0][6]/Q -type DFF DFF
add mapped point mem[0][7]/q mem_reg[0][7]/Q -type DFF DFF
add mapped point mem[0][10]/q mem_reg[0][10]/Q -type DFF DFF
add mapped point mem[0][11]/q mem_reg[0][11]/Q -type DFF DFF
add mapped point mem[4][0]/q mem_reg[4][0]/Q -type DFF DFF
add mapped point mem[4][1]/q mem_reg[4][1]/Q -type DFF DFF
add mapped point mem[4][2]/q mem_reg[4][2]/Q -type DFF DFF
add mapped point mem[4][3]/q mem_reg[4][3]/Q -type DFF DFF
add mapped point mem[4][5]/q mem_reg[4][5]/Q -type DFF DFF
add mapped point mem[4][6]/q mem_reg[4][6]/Q -type DFF DFF
add mapped point mem[0][12]/q mem_reg[0][12]/Q -type DFF DFF
add mapped point mem[4][8]/q mem_reg[4][8]/Q -type DFF DFF
add mapped point mem[0][13]/q mem_reg[0][13]/Q -type DFF DFF
add mapped point mem[4][18]/q mem_reg[4][18]/Q -type DFF DFF
add mapped point mem[4][19]/q mem_reg[4][19]/Q -type DFF DFF
add mapped point mem[4][21]/q mem_reg[4][21]/Q -type DFF DFF
add mapped point mem[0][15]/q mem_reg[0][15]/Q -type DFF DFF
add mapped point mem[0][16]/q mem_reg[0][16]/Q -type DFF DFF
add mapped point mem[4][20]/q mem_reg[4][20]/Q -type DFF DFF
add mapped point mem[4][22]/q mem_reg[4][22]/Q -type DFF DFF
add mapped point mem[4][23]/q mem_reg[4][23]/Q -type DFF DFF
add mapped point mem[4][25]/q mem_reg[4][25]/Q -type DFF DFF
add mapped point mem[0][17]/q mem_reg[0][17]/Q -type DFF DFF
add mapped point mem[4][26]/q mem_reg[4][26]/Q -type DFF DFF
add mapped point mem[4][7]/q mem_reg[4][7]/Q -type DFF DFF
add mapped point mem[4][29]/q mem_reg[4][29]/Q -type DFF DFF
add mapped point mem[4][30]/q mem_reg[4][30]/Q -type DFF DFF
add mapped point mem[4][31]/q mem_reg[4][31]/Q -type DFF DFF
add mapped point mem[0][19]/q mem_reg[0][19]/Q -type DFF DFF
add mapped point mem[0][20]/q mem_reg[0][20]/Q -type DFF DFF
add mapped point mem[0][21]/q mem_reg[0][21]/Q -type DFF DFF
add mapped point mem[4][28]/q mem_reg[4][28]/Q -type DFF DFF
add mapped point mem[4][9]/q mem_reg[4][9]/Q -type DFF DFF
add mapped point mem[4][11]/q mem_reg[4][11]/Q -type DFF DFF
add mapped point mem[4][24]/q mem_reg[4][24]/Q -type DFF DFF
add mapped point mem[4][12]/q mem_reg[4][12]/Q -type DFF DFF
add mapped point mem[0][14]/q mem_reg[0][14]/Q -type DFF DFF
add mapped point mem[4][14]/q mem_reg[4][14]/Q -type DFF DFF
add mapped point mem[4][15]/q mem_reg[4][15]/Q -type DFF DFF
add mapped point mem[4][17]/q mem_reg[4][17]/Q -type DFF DFF
add mapped point mem[4][16]/q mem_reg[4][16]/Q -type DFF DFF
add mapped point mem[4][10]/q mem_reg[4][10]/Q -type DFF DFF
add mapped point mem[0][31]/q mem_reg[0][31]/Q -type DFF DFF
add mapped point mem[4][13]/q mem_reg[4][13]/Q -type DFF DFF
add mapped point mem[6][0]/q mem_reg[6][0]/Q -type DFF DFF
add mapped point mem[6][30]/q mem_reg[6][30]/Q -type DFF DFF
add mapped point mem[7][30]/q mem_reg[7][30]/Q -type DFF DFF
add mapped point mem[5][13]/q mem_reg[5][13]/Q -type DFF DFF
add mapped point mem[5][14]/q mem_reg[5][14]/Q -type DFF DFF
add mapped point mem[5][16]/q mem_reg[5][16]/Q -type DFF DFF
add mapped point mem[5][17]/q mem_reg[5][17]/Q -type DFF DFF
add mapped point mem[7][23]/q mem_reg[7][23]/Q -type DFF DFF
add mapped point mem[5][19]/q mem_reg[5][19]/Q -type DFF DFF
add mapped point mem[5][20]/q mem_reg[5][20]/Q -type DFF DFF
add mapped point mem[5][21]/q mem_reg[5][21]/Q -type DFF DFF
add mapped point mem[5][22]/q mem_reg[5][22]/Q -type DFF DFF
add mapped point mem[5][23]/q mem_reg[5][23]/Q -type DFF DFF
add mapped point mem[3][4]/q mem_reg[3][4]/Q -type DFF DFF
add mapped point mem[5][24]/q mem_reg[5][24]/Q -type DFF DFF
add mapped point mem[5][25]/q mem_reg[5][25]/Q -type DFF DFF
add mapped point mem[5][26]/q mem_reg[5][26]/Q -type DFF DFF
add mapped point mem[5][27]/q mem_reg[5][27]/Q -type DFF DFF
add mapped point mem[5][28]/q mem_reg[5][28]/Q -type DFF DFF
add mapped point mem[3][12]/q mem_reg[3][12]/Q -type DFF DFF
add mapped point mem[5][29]/q mem_reg[5][29]/Q -type DFF DFF
add mapped point mem[5][30]/q mem_reg[5][30]/Q -type DFF DFF
add mapped point mem[5][31]/q mem_reg[5][31]/Q -type DFF DFF
add mapped point mem[7][2]/q mem_reg[7][2]/Q -type DFF DFF
add mapped point mem[6][1]/q mem_reg[6][1]/Q -type DFF DFF
add mapped point mem[6][3]/q mem_reg[6][3]/Q -type DFF DFF
add mapped point mem[6][4]/q mem_reg[6][4]/Q -type DFF DFF
add mapped point mem[6][5]/q mem_reg[6][5]/Q -type DFF DFF
add mapped point mem[6][6]/q mem_reg[6][6]/Q -type DFF DFF
add mapped point mem[6][7]/q mem_reg[6][7]/Q -type DFF DFF
add mapped point mem[6][8]/q mem_reg[6][8]/Q -type DFF DFF
add mapped point mem[6][9]/q mem_reg[6][9]/Q -type DFF DFF
add mapped point mem[6][10]/q mem_reg[6][10]/Q -type DFF DFF
add mapped point mem[6][11]/q mem_reg[6][11]/Q -type DFF DFF
add mapped point mem[6][12]/q mem_reg[6][12]/Q -type DFF DFF
add mapped point mem[6][13]/q mem_reg[6][13]/Q -type DFF DFF
add mapped point mem[6][14]/q mem_reg[6][14]/Q -type DFF DFF
add mapped point mem[6][15]/q mem_reg[6][15]/Q -type DFF DFF
add mapped point mem[6][16]/q mem_reg[6][16]/Q -type DFF DFF
add mapped point mem[6][17]/q mem_reg[6][17]/Q -type DFF DFF
add mapped point mem[5][2]/q mem_reg[5][2]/Q -type DFF DFF
add mapped point mem[6][19]/q mem_reg[6][19]/Q -type DFF DFF
add mapped point mem[6][20]/q mem_reg[6][20]/Q -type DFF DFF
add mapped point mem[7][25]/q mem_reg[7][25]/Q -type DFF DFF
add mapped point mem[6][21]/q mem_reg[6][21]/Q -type DFF DFF
add mapped point mem[6][22]/q mem_reg[6][22]/Q -type DFF DFF
add mapped point mem[6][18]/q mem_reg[6][18]/Q -type DFF DFF
add mapped point mem[6][31]/q mem_reg[6][31]/Q -type DFF DFF
add mapped point mem[3][1]/q mem_reg[3][1]/Q -type DFF DFF
add mapped point mem[7][0]/q mem_reg[7][0]/Q -type DFF DFF
add mapped point mem[7][1]/q mem_reg[7][1]/Q -type DFF DFF
add mapped point mem[3][2]/q mem_reg[3][2]/Q -type DFF DFF
add mapped point mem[3][3]/q mem_reg[3][3]/Q -type DFF DFF
add mapped point mem[7][3]/q mem_reg[7][3]/Q -type DFF DFF
add mapped point mem[7][4]/q mem_reg[7][4]/Q -type DFF DFF
add mapped point mem[5][8]/q mem_reg[5][8]/Q -type DFF DFF
add mapped point mem[7][5]/q mem_reg[7][5]/Q -type DFF DFF
add mapped point mem[3][5]/q mem_reg[3][5]/Q -type DFF DFF
add mapped point mem[7][6]/q mem_reg[7][6]/Q -type DFF DFF
add mapped point mem[7][7]/q mem_reg[7][7]/Q -type DFF DFF
add mapped point mem[7][8]/q mem_reg[7][8]/Q -type DFF DFF
add mapped point mem[7][9]/q mem_reg[7][9]/Q -type DFF DFF
add mapped point mem[7][10]/q mem_reg[7][10]/Q -type DFF DFF
add mapped point mem[3][7]/q mem_reg[3][7]/Q -type DFF DFF
add mapped point mem[7][11]/q mem_reg[7][11]/Q -type DFF DFF
add mapped point mem[3][8]/q mem_reg[3][8]/Q -type DFF DFF
add mapped point mem[7][13]/q mem_reg[7][13]/Q -type DFF DFF
add mapped point mem[6][24]/q mem_reg[6][24]/Q -type DFF DFF
add mapped point mem[7][15]/q mem_reg[7][15]/Q -type DFF DFF
add mapped point mem[3][9]/q mem_reg[3][9]/Q -type DFF DFF
add mapped point mem[7][16]/q mem_reg[7][16]/Q -type DFF DFF
add mapped point mem[7][17]/q mem_reg[7][17]/Q -type DFF DFF
add mapped point mem[3][10]/q mem_reg[3][10]/Q -type DFF DFF
add mapped point mem[7][18]/q mem_reg[7][18]/Q -type DFF DFF
add mapped point mem[3][11]/q mem_reg[3][11]/Q -type DFF DFF
add mapped point mem[7][19]/q mem_reg[7][19]/Q -type DFF DFF
add mapped point mem[7][20]/q mem_reg[7][20]/Q -type DFF DFF
add mapped point mem[7][21]/q mem_reg[7][21]/Q -type DFF DFF
add mapped point mem[7][22]/q mem_reg[7][22]/Q -type DFF DFF
add mapped point mem[3][13]/q mem_reg[3][13]/Q -type DFF DFF
add mapped point mem[7][24]/q mem_reg[7][24]/Q -type DFF DFF
add mapped point mem[5][10]/q mem_reg[5][10]/Q -type DFF DFF
add mapped point mem[5][11]/q mem_reg[5][11]/Q -type DFF DFF
add mapped point mem[5][12]/q mem_reg[5][12]/Q -type DFF DFF
add mapped point mem[6][23]/q mem_reg[6][23]/Q -type DFF DFF
add mapped point mem[5][7]/q mem_reg[5][7]/Q -type DFF DFF
add mapped point mem[5][6]/q mem_reg[5][6]/Q -type DFF DFF
add mapped point mem[5][5]/q mem_reg[5][5]/Q -type DFF DFF
add mapped point mem[5][4]/q mem_reg[5][4]/Q -type DFF DFF
add mapped point mem[5][3]/q mem_reg[5][3]/Q -type DFF DFF
add mapped point mem[5][1]/q mem_reg[5][1]/Q -type DFF DFF
add mapped point mem[5][0]/q mem_reg[5][0]/Q -type DFF DFF
add mapped point mem[5][9]/q mem_reg[5][9]/Q -type DFF DFF
add mapped point mem[3][31]/q mem_reg[3][31]/Q -type DFF DFF
add mapped point mem[3][30]/q mem_reg[3][30]/Q -type DFF DFF
add mapped point mem[3][29]/q mem_reg[3][29]/Q -type DFF DFF
add mapped point mem[3][28]/q mem_reg[3][28]/Q -type DFF DFF
add mapped point mem[3][27]/q mem_reg[3][27]/Q -type DFF DFF
add mapped point mem[3][26]/q mem_reg[3][26]/Q -type DFF DFF
add mapped point mem[6][26]/q mem_reg[6][26]/Q -type DFF DFF
add mapped point mem[3][25]/q mem_reg[3][25]/Q -type DFF DFF
add mapped point mem[3][24]/q mem_reg[3][24]/Q -type DFF DFF
add mapped point mem[3][23]/q mem_reg[3][23]/Q -type DFF DFF
add mapped point mem[3][22]/q mem_reg[3][22]/Q -type DFF DFF
add mapped point mem[3][21]/q mem_reg[3][21]/Q -type DFF DFF
add mapped point mem[3][20]/q mem_reg[3][20]/Q -type DFF DFF
add mapped point mem[3][19]/q mem_reg[3][19]/Q -type DFF DFF
add mapped point mem[3][18]/q mem_reg[3][18]/Q -type DFF DFF
add mapped point mem[3][17]/q mem_reg[3][17]/Q -type DFF DFF
add mapped point mem[7][31]/q mem_reg[7][31]/Q -type DFF DFF
add mapped point mem[3][16]/q mem_reg[3][16]/Q -type DFF DFF
add mapped point mem[7][29]/q mem_reg[7][29]/Q -type DFF DFF
add mapped point mem[3][14]/q mem_reg[3][14]/Q -type DFF DFF
add mapped point mem[7][28]/q mem_reg[7][28]/Q -type DFF DFF
add mapped point mem[7][27]/q mem_reg[7][27]/Q -type DFF DFF
add mapped point mem[3][15]/q mem_reg[3][15]/Q -type DFF DFF
add mapped point mem[7][26]/q mem_reg[7][26]/Q -type DFF DFF
add mapped point mem[6][27]/q mem_reg[6][27]/Q -type DFF DFF
add mapped point mem[5][18]/q mem_reg[5][18]/Q -type DFF DFF
add mapped point mem[6][28]/q mem_reg[6][28]/Q -type DFF DFF
add mapped point mem[7][14]/q mem_reg[7][14]/Q -type DFF DFF
add mapped point mem[3][0]/q mem_reg[3][0]/Q -type DFF DFF
add mapped point mem[7][12]/q mem_reg[7][12]/Q -type DFF DFF
add mapped point mem[6][2]/q mem_reg[6][2]/Q -type DFF DFF
add mapped point mem[6][29]/q mem_reg[6][29]/Q -type DFF DFF
add mapped point mem[3][6]/q mem_reg[3][6]/Q -type DFF DFF
add mapped point mem[5][15]/q mem_reg[5][15]/Q -type DFF DFF
add mapped point mem[6][25]/q mem_reg[6][25]/Q -type DFF DFF
add mapped point mem[1][29]/q mem_reg[1][29]/Q -type DFF DFF
add mapped point mem[2][17]/q mem_reg[2][17]/Q -type DFF DFF
add mapped point mem[1][8]/q mem_reg[1][8]/Q -type DFF DFF
add mapped point mem[2][16]/q mem_reg[2][16]/Q -type DFF DFF
add mapped point mem[2][14]/q mem_reg[2][14]/Q -type DFF DFF
add mapped point mem[2][24]/q mem_reg[2][24]/Q -type DFF DFF
add mapped point mem[2][13]/q mem_reg[2][13]/Q -type DFF DFF
add mapped point mem[2][25]/q mem_reg[2][25]/Q -type DFF DFF
add mapped point mem[2][15]/q mem_reg[2][15]/Q -type DFF DFF
add mapped point mem[1][6]/q mem_reg[1][6]/Q -type DFF DFF
add mapped point mem[1][7]/q mem_reg[1][7]/Q -type DFF DFF
add mapped point mem[1][21]/q mem_reg[1][21]/Q -type DFF DFF
add mapped point mem[1][25]/q mem_reg[1][25]/Q -type DFF DFF
add mapped point mem[1][3]/q mem_reg[1][3]/Q -type DFF DFF
add mapped point mem[2][1]/q mem_reg[2][1]/Q -type DFF DFF
add mapped point mem[2][23]/q mem_reg[2][23]/Q -type DFF DFF
add mapped point mem[1][15]/q mem_reg[1][15]/Q -type DFF DFF
add mapped point mem[1][13]/q mem_reg[1][13]/Q -type DFF DFF
add mapped point mem[2][5]/q mem_reg[2][5]/Q -type DFF DFF
add mapped point mem[1][11]/q mem_reg[1][11]/Q -type DFF DFF
add mapped point mem[2][4]/q mem_reg[2][4]/Q -type DFF DFF
add mapped point mem[1][0]/q mem_reg[1][0]/Q -type DFF DFF
add mapped point mem[1][12]/q mem_reg[1][12]/Q -type DFF DFF
add mapped point mem[1][16]/q mem_reg[1][16]/Q -type DFF DFF
add mapped point mem[2][11]/q mem_reg[2][11]/Q -type DFF DFF
add mapped point mem[2][28]/q mem_reg[2][28]/Q -type DFF DFF
add mapped point mem[2][31]/q mem_reg[2][31]/Q -type DFF DFF
add mapped point mem[1][1]/q mem_reg[1][1]/Q -type DFF DFF
add mapped point mem[1][2]/q mem_reg[1][2]/Q -type DFF DFF
add mapped point mem[1][4]/q mem_reg[1][4]/Q -type DFF DFF
add mapped point mem[2][18]/q mem_reg[2][18]/Q -type DFF DFF
add mapped point mem[1][5]/q mem_reg[1][5]/Q -type DFF DFF
add mapped point mem[1][19]/q mem_reg[1][19]/Q -type DFF DFF
add mapped point mem[2][19]/q mem_reg[2][19]/Q -type DFF DFF
add mapped point mem[2][3]/q mem_reg[2][3]/Q -type DFF DFF
add mapped point mem[2][2]/q mem_reg[2][2]/Q -type DFF DFF
add mapped point mem[2][0]/q mem_reg[2][0]/Q -type DFF DFF
add mapped point mem[1][31]/q mem_reg[1][31]/Q -type DFF DFF
add mapped point mem[1][30]/q mem_reg[1][30]/Q -type DFF DFF
add mapped point mem[1][28]/q mem_reg[1][28]/Q -type DFF DFF
add mapped point mem[1][27]/q mem_reg[1][27]/Q -type DFF DFF
add mapped point mem[1][26]/q mem_reg[1][26]/Q -type DFF DFF
add mapped point mem[1][24]/q mem_reg[1][24]/Q -type DFF DFF
add mapped point mem[1][23]/q mem_reg[1][23]/Q -type DFF DFF
add mapped point mem[1][22]/q mem_reg[1][22]/Q -type DFF DFF
add mapped point mem[2][22]/q mem_reg[2][22]/Q -type DFF DFF
add mapped point mem[1][20]/q mem_reg[1][20]/Q -type DFF DFF
add mapped point mem[1][18]/q mem_reg[1][18]/Q -type DFF DFF
add mapped point mem[1][14]/q mem_reg[1][14]/Q -type DFF DFF
add mapped point mem[1][9]/q mem_reg[1][9]/Q -type DFF DFF
add mapped point mem[1][10]/q mem_reg[1][10]/Q -type DFF DFF
add mapped point mem[2][12]/q mem_reg[2][12]/Q -type DFF DFF
add mapped point mem[2][21]/q mem_reg[2][21]/Q -type DFF DFF
add mapped point mem[1][17]/q mem_reg[1][17]/Q -type DFF DFF
add mapped point mem[2][8]/q mem_reg[2][8]/Q -type DFF DFF
add mapped point mem[2][7]/q mem_reg[2][7]/Q -type DFF DFF
add mapped point mem[2][29]/q mem_reg[2][29]/Q -type DFF DFF
add mapped point mem[2][6]/q mem_reg[2][6]/Q -type DFF DFF
add mapped point mem[2][26]/q mem_reg[2][26]/Q -type DFF DFF
add mapped point mem[2][9]/q mem_reg[2][9]/Q -type DFF DFF
add mapped point mem[2][10]/q mem_reg[2][10]/Q -type DFF DFF
add mapped point mem[2][20]/q mem_reg[2][20]/Q -type DFF DFF
add mapped point mem[2][30]/q mem_reg[2][30]/Q -type DFF DFF
add mapped point mem[2][27]/q mem_reg[2][27]/Q -type DFF DFF
add mapped point rd_ptr[1]/q rd_ptr_reg[1]/Q -type DFF DFF
add mapped point wr_ptr[0]/q wr_ptr_reg[0]/Q -type DFF DFF
add mapped point rd_ptr[2]/q rd_ptr_reg[2]/Q -type DFF DFF
add mapped point count[0]/q count_reg[0]/Q -type DFF DFF
add mapped point wr_ptr[1]/q wr_ptr_reg[1]/Q -type DFF DFF
add mapped point wr_ptr[2]/q wr_ptr_reg[2]/Q -type DFF DFF
add mapped point count[2]/q count_reg[2]/Q -type DFF DFF
add mapped point rd_ptr[0]/q rd_ptr_reg[0]/Q -type DFF DFF
add mapped point count[1]/q count_reg[1]/Q -type DFF DFF
add mapped point count[3]/q count_reg[3]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
