
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  9 2026 18:26:58 KST (Jul  9 2026 09:26:58 UTC)

// Verification Directory fv/traffic_light 

module traffic_light(clk, rst_n, o_red, o_yellow, o_green);
  input clk, rst_n;
  output o_red, o_yellow, o_green;
  wire clk, rst_n;
  wire o_red, o_yellow, o_green;
  wire [1:0] r_state;
  wire [1:0] r_cnt;
  wire n_1, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_11, n_13, n_14, n_15;
  DFFHQX1 \r_state_reg[0] (.CK (clk), .D (n_14), .Q (r_state[0]));
  DFFHQX1 \r_state_reg[1] (.CK (clk), .D (n_15), .Q (r_state[1]));
  AND2X1 g436__2398(.A (n_11), .B (rst_n), .Y (n_15));
  AND2X1 g435__5107(.A (n_13), .B (rst_n), .Y (n_14));
  MX2X1 g439__6260(.A (o_green), .B (r_state[0]), .S0 (n_9), .Y (n_13));
  MX2X1 g438__4319(.A (o_yellow), .B (r_state[1]), .S0 (n_9), .Y
       (n_11));
  DFFHQX1 \r_cnt_reg[1] (.CK (clk), .D (n_8), .Q (r_cnt[1]));
  OAI2BB1X1 g440__8428(.A0N (r_cnt[1]), .A1N (n_7), .B0 (n_6), .Y
       (n_8));
  AOI32X1 g442__5526(.A0 (r_cnt[1]), .A1 (r_cnt[0]), .A2 (n_5), .B0
       (r_state[0]), .B1 (n_4), .Y (n_9));
  DFFHQX1 \r_cnt_reg[0] (.CK (clk), .D (n_7), .Q (r_cnt[0]));
  NAND3XL g444__6783(.A (rst_n), .B (n_5), .C (n_3), .Y (n_6));
  AOI211XL g443__3680(.A0 (r_state[1]), .A1 (r_state[0]), .B0 (n_1),
       .C0 (r_cnt[0]), .Y (n_7));
  OR2X1 g445__1617(.A (r_state[1]), .B (n_3), .Y (n_4));
  NOR2XL g449__2802(.A (r_state[1]), .B (n_5), .Y (o_yellow));
  NOR2XL g446__5122(.A (r_state[1]), .B (r_state[0]), .Y (o_green));
  NOR2BX1 g447__8246(.AN (r_cnt[0]), .B (r_cnt[1]), .Y (n_3));
  INVXL g452(.A (r_state[0]), .Y (n_5));
  INVXL g450(.A (rst_n), .Y (n_1));
  NOR2BX1 g2(.AN (r_state[1]), .B (r_state[0]), .Y (o_red));
endmodule

