
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  9 2026 00:33:45 KST (Jul  8 2026 15:33:45 UTC)

// Verification Directory fv/gpio_mux 

module gpio_mux(i_sel, i_uartTx, i_uartRx, i_pwm, i_peri, o_gpio);
  input [1:0] i_sel;
  input i_uartTx, i_uartRx, i_pwm, i_peri;
  output o_gpio;
  wire [1:0] i_sel;
  wire i_uartTx, i_uartRx, i_pwm, i_peri;
  wire o_gpio;
  MX4XL g148__2398(.A (i_uartTx), .B (i_pwm), .C (i_uartRx), .D
       (i_peri), .S0 (i_sel[1]), .S1 (i_sel[0]), .Y (o_gpio));
endmodule

